function [fitresult, gof] = getFit4V(time, V, graph, axesV)
%CREATEFIT(TIME,V3)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : time
%      Y Output: V
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Jan-2013 14:03:58


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( time, V );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [0 0 -Inf];
opts.Robust = 'Bisquare';
opts.StartPoint = [5 0.01 1];
opts.Upper = [Inf Inf 0];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
if(graph)
    % Plot fit with data.
    figure(5);
    box(axesV,'on');
    hold(axesV,'all');
    h = plot(xData,fitresult(xData),'k','Parent',axesV,'LineWidth',2);
    h = plot(xData,yData,'+k','Parent',axesV,'LineWidth',2,'MarkerSize',2);
    
%     legend( h, 'V3 vs. time', 'untitled fit 1', 'Location', 'NorthEast' );
%     % Label axes
%     xlabel( 'time' );
%     ylabel( 'V' );
%     grid on
end
   


