function tit=vectorialFieldFigure(X1, Y1, U1, V1, x_lim,y_lim, t,levelList,fig)
%CREATEFIGURE(X1,Y1,U1,V1)
%  X1:  quiver x
%  Y1:  quiver y
%  U1:  quiver u 
%  V1:  quiver v

%  Auto-generated by MATLAB on 03-Dec-2012 12:00:13

% Create figure
%close(figure(1))

figure1 = fig;
set(figure1,'Color',[1 1 1]);
clf(figure1);

% Create axes
axes1 = axes('Parent',figure1,'FontSize',20);
ylim(axes1,y_lim);
xlim(axes1,x_lim);
box(axes1,'on');
hold(axes1,'all');

% Create quiver
m=size(unique(X1),1);
n=size(unique(Y1),1);
XX=reshape(X1,m,n);
YY=reshape(Y1,m,n);
ZZ=reshape((U1.^2+V1.^2).^0.5,m,n);
[C, hdl]=contour(axes1,XX,YY,ZZ,'Fill','on');
supe=100;
infe=1;
if(~isempty(levelList))
    maxZ=max(ZZ(:));
    maxL=max(levelList);
    minZ=min(ZZ(:));
    minL=min(levelList);
    if(maxZ<maxL && maxZ>0)
        supe=round((maxZ-minL)/(maxL-minL)*100);
    end
    if(minZ>minL)
        infe=round(minZ/(maxL-minL)*100);
    end
   set(hdl,'LevelList',levelList)
end
colmap=(1-jet(100))*0.25+jet(100);
colormap(figure1,colmap(infe:supe,:));


shading(axes1, 'interp');

quiver(axes1,X1,Y1,U1,V1,2,'k');
colorbar('peer',axes1,'FontSize',15);


% Create xlabel
xlabel(axes1,'x (mm)','FontSize',25);

% Create ylabel
ylabel(axes1,'y (mm)','FontSize',25);

% Create title
tit=title(axes1,['Velocity field at ' num2str(t) ' ms'],'FontWeight','bold','FontSize',20,...
    'FontName','Helvetica');